name: Rails Mongo Redis Test

on:
  workflow_dispatch:

jobs:
  rspec:
    name: Rspec
    runs-on: ubuntu-latest

    # https://github.com/actions/example-services/tree/master/.github/workflows
    services:
      mongo:
        image: healthcheck/mongo
        ports: ['27017:27017']
      redis:
        image: redis
        ports: ['6379:6379']
        options: --entrypoint redis-server

    env:
      RAILS_ENV: test
      DB_TEST: mongodb://localhost:27017/imob2u_test
      MAILER_ADDRESS: noreply+test@imob2u.com.br

    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - name: Create DB
        run: bin/rails db:setup db:test:prepare
      - name: Rspec
        run: bundle exec rspec
